#!/usr/bin/env python
import serial
import rospy
#import numpy as np
from geometry_msgs.msg import Twist

arduino = serial.Serial('/dev/ttyACM0',115200)

def callback(data):
    x = data.linear.x
    z = data.angular.z
    c = str(x)+','+str(z)+'\n'
    print(x)
    print(z)
    arduino.write(c)

def listener():

	# In ROS, nodes are uniquely named. If two nodes with the same
	# name are launched, the previous one is kicked off. The
	# anonymous=True flag means that rospy will choose a unique
	# name for our 'listener' node so that multiple listeners can
	# run simultaneously.
	rospy.init_node('listener')

	rospy.Subscriber("/Diff_Drive/diff_drive_controller/cmd_vel", Twist, callback)

	# spin() simply keeps python from exiting until this node is stopped
	rospy.spin()

if __name__ == '__main__':
	listener()
